version: '3.8'

services:
  api:
    image: api:latest
    ports:
      - '9000:3333'
    environment:
      PORT: '3333'
      APP_DB_HOST: 'db'
      APP_DB_PORT: '5432'
      APP_DB_USER: $APP_DB_USER
      APP_DB_PASS: $APP_DB_PASS
      APP_DB_NAME: $APP_DB_NAME
      APP_DB_SCHEMA: $APP_DB_SCHEMA

  db:
    image: postgres:16
    ports:
      - '9001:5432'
    volumes:
      - ./apps/system/db/volumes/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      APP_DB_USER: $APP_DB_USER
      APP_DB_PASS: $APP_DB_PASS
      APP_DB_NAME: $APP_DB_NAME
      APP_DB_SCHEMA: $APP_DB_SCHEMA
